###Получение списка сотрудников
GET http://localhost:8080/employee
###Добавление сотрудника
POST http://localhost:8080/employee
Content-Type: application/json

{
  "firstName": "Test",
  "lastName": "Test",
  "secondName": "Test",
  "department": 1,
  "salary": 1000
}
###Добавление сотрудника2
POST http://localhost:8080/employee
Content-Type: application/json

{
  "firstName": "fdsa",
  "lastName": "asdf",
  "secondName": "fds",
  "department": 2,
  "salary": 2000
}
###Добавление сотрудника3
POST http://localhost:8080/employee
Content-Type: application/json

{
  "firstName": "fds2a",
  "lastName": "asd3f",
  "secondName": "fd s",
  "department": 2,
  "salary": 2000
}
### Получение суммы зарплат сотрудников
GET http://localhost:8080/employee/salary/sum

### Получение сотрудника с минимальной зарплатой
GET http://localhost:8080/employee/salary/min

### Получение сотрудника с максимальной зарплатой
GET http://localhost:8080/employee/salary/max

### Получение всех сотрудников, зарплата которых больше средней зарплаты
GET http://localhost:8080/employee/high-salary?salary=1500